"""
DSP W2V-BERT Code-Switching ASR Model
======================================
Architecture:
  Audio → [LoRA-Adapted W2V-BERT-2.0] → features [B, T, 1024]
               ↓
          CausalPromptGenerator (Causal GRU)
            - Reads features stream-by-stream (for real-time LID)
            - Outputs 1: LID logits [B, T, 3] and GRU hidden state (for streaming)
            - Outputs 2: Acoustic Prompt [B, T, 256]
               ↓
  [Feature Injection] 
  Final_Features = features + Tanh(Gate) * Linear(Acoustic_Prompt)
  
Adaptation Strategy (Hybrid):
  - LoRA (Low-Rank Adaptation) is injected into ALL Linear layers of the W2V-BERT backbone
    via SpeechBrain's AdaptedModel. This provides state-of-the-art PEFT.
  - Frame-synchronous Acoustic Prompting: the output of the Causal GRU is injected
    back into the feature stream via a learnable Tanh gate before final ASR decoding.
"""

import torch
import torch.nn as nn
from speechbrain.lobes.models.huggingface_wav2vec import HuggingFaceWav2Vec2
from speechbrain.nnet.adapters import AdaptedModel, LoRA
from speechbrain.nnet.normalization import LayerNorm


class CausalPromptGenerator(nn.Module):
    """
    Causal GRU-based Language ID (LID) predictor for streaming code-switching ASR.

    Since LoRA now handles feature adaptation inside the backbone,
    this module's sole responsibility is:
      1. Predicting per-frame language labels (VI / EN / SIL)
      2. Maintaining a causal hidden state for streaming chunk-by-chunk inference

    Arguments
    ---------
    input_size : int
        Dimension of backbone features (default: 1024 for w2v-bert-2.0).
    hidden_size : int
        GRU hidden dimension (default: 256).
    num_languages : int
        Number of language classes (default: 3 — VI, EN, SIL).
    dropout : float
        Dropout probability after GRU (prevents overfitting on small CS datasets).
    """

    def __init__(self, input_size=1024, hidden_size=256, num_languages=3, dropout=0.1):
        super().__init__()

        # Causal GRU: bidirectional=False ensures no future chunk is seen (streaming safe)
        self.gru = nn.GRU(
            input_size=input_size,
            hidden_size=hidden_size,
            batch_first=True,
            bidirectional=False,
        )

        # Dropout → LayerNorm pipeline (from SpeechBrain LibriSpeech seq2seq recipe)
        self.dropout = nn.Dropout(p=dropout)
        self.norm = LayerNorm(input_size=hidden_size)

        # LID classification head: [B, T, hidden] → [B, T, num_languages]
        self.lid_head = nn.Linear(hidden_size, num_languages)

    def forward(self, features, hx=None):
        """
        Arguments
        ---------
        features : torch.Tensor
            Backbone output features of shape [batch, time, input_size].
        hx : torch.Tensor, optional
            Previous GRU hidden state [num_layers, batch, hidden_size].
            Pass None for the first chunk; pass the returned hx_new for subsequent chunks.

        Returns
        -------
        lid_logits : torch.Tensor
            Raw (pre-softmax) LID predictions [batch, time, num_languages].
        prompt : torch.Tensor
            The acoustic prompt vector [batch, time, hidden_size] to be injected.
        hx_new : torch.Tensor
            Updated GRU hidden state [num_layers, batch, hidden_size] for next chunk.
        """
        # [B, T, hidden], [1, B, hidden]
        gru_out, hx_new = self.gru(features, hx)
        gru_out = self.norm(self.dropout(gru_out))  # Dropout → LayerNorm

        # LID predictions: raw logits (apply log_softmax in Brain.compute_objectives)
        lid_logits = self.lid_head(gru_out)

        return lid_logits, gru_out, hx_new


class DSP_W2VBERT(nn.Module):
    """
    Semi-Supervised Causal Streaming Code-Switching ASR model.

    Combines:
      - W2V-BERT-2.0 backbone with LoRA PEFT adapters
      - CausalPromptGenerator for per-frame LID prediction + streaming state
      - Frame-synchronous Acoustic Prompt Injection (Feature + Tanh(Gate) * Prompt)

    The backbone is adapted using SpeechBrain's AdaptedModel + LoRA, which is the
    professional industry-standard PEFT technique. Simultaneously, the acoustic prompt 
    generated by the parallel GRU is injected back into the final feature stream 
    to provide dynamic, frame-synchronous context switching before the CTC decoder.

    Arguments
    ---------
    source : str
        HuggingFace model ID for W2V-BERT-2.0 backbone.
    save_path : str
        Local path to cache the backbone.
    input_size : int
        Backbone output feature dimension (1024 for w2v-bert-2.0).
    hidden_size : int
        GRU hidden size in CausalPromptGenerator.
    num_languages : int
        LID class count (VI=1, EN=2, SIL=0).
    lora_rank : int
        LoRA rank r. Lower = fewer params. Recommended: 8–32.
    lora_alpha : float
        LoRA scaling factor α. Scaling = α/r. Default: 1.0.
    dropout : float
        Dropout in CausalPromptGenerator's GRU.
    """

    def __init__(
        self,
        source="facebook/w2v-bert-2.0",
        save_path="pretrained_models",
        input_size=1024,
        hidden_size=256,
        num_languages=3,
        lora_rank=16,
        lora_alpha=1.0,
        dropout=0.1,
    ):
        super().__init__()

        # 1. Load base backbone (NOT frozen — LoRA will manage which params are trainable)
        base_backbone = HuggingFaceWav2Vec2(
            source=source,
            save_path=save_path,
            freeze=False,  # LoRA freezes pretrained params internally via AdaptedModel
        )

        # 2. Wrap backbone with SpeechBrain AdaptedModel + LoRA (Hard Fix #5)
        #    This replaces the manual `gate = nn.Parameter(torch.zeros(input_size))`.
        #    AdaptedModel:
        #      - Freezes ALL backbone params (requires_grad=False)
        #      - Replaces every Linear layer with LoRA(Linear) (adds trainable rank-r matrices)
        #      - Is checkpoint-safe: saves only LoRA params, not the full backbone
        self.backbone = AdaptedModel(
            model_to_adapt=base_backbone,
            adapter_class=LoRA,
            all_linear=True,           # Adapt ALL Linear layers in W2V-BERT
            adapter_kwargs={
                "rank": lora_rank,     # r=16 → 2*1024*16 = 32768 extra params per layer
                "alpha": lora_alpha,   # scaling = alpha/rank
            },
        )

        # 3. CausalPromptGenerator for streaming LID + hidden state management
        self.prompt_generator = CausalPromptGenerator(
            input_size=input_size,
            hidden_size=hidden_size,
            num_languages=num_languages,
            dropout=dropout,
        )

        # 4. Hybrid Acoustic Prompt Injection Mechanism
        # Projects the GRU's hidden_size (256) back to the backbone's input_size (1024)
        self.prompt_proj = nn.Linear(hidden_size, input_size)
        # Xavier init for prompt_proj: prevents vanishing gradients at training start.
        # (LoRA features are well-trained; random proj weights would dominate without this)
        nn.init.xavier_uniform_(self.prompt_proj.weight)
        nn.init.zeros_(self.prompt_proj.bias)
        
        # Dropout before injection: prevents noisy early-training prompts from
        # destabilizing the pre-trained LoRA features.
        self.prompt_dropout = nn.Dropout(p=dropout)
        
        # Learnable gating scalar per channel to control the influence of the prompt
        self.gate = nn.Parameter(torch.zeros(input_size))

    def forward(self, wav, wav_lens=None, hx=None):
        """
        Arguments
        ---------
        wav : torch.Tensor
            Raw waveform [batch, time_samples]. 16kHz mono.
        wav_lens : torch.Tensor
            Relative lengths [batch], values in [0.0, 1.0].
        hx : torch.Tensor, optional
            GRU hidden state from previous chunk [1, batch, hidden_size].
            None for first chunk or non-streaming training.

        Returns
        -------
        adapted_features : torch.Tensor
            LoRA-adapted backbone features [batch, time_frames, input_size].
        lid_logits : torch.Tensor
            Per-frame LID raw logits [batch, time_frames, num_languages].
        hx_new : torch.Tensor
            Updated GRU hidden state [1, batch, hidden_size] for next chunk.
        """
        # 1. LoRA-adapted feature extraction [B, T, 1024]
        #    LoRA adapters inside each Linear layer of W2V-BERT modify the internal representations.
        adapted_features = self.backbone(wav, wav_lens)

        # 2. Causal LID prediction & Acoustic Prompt Generation
        lid_logits, prompt, hx_new = self.prompt_generator(adapted_features, hx)

        # 3. Frame-synchronous Acoustic Prompt Injection
        #    Final_Features = Feature + Tanh(Gate) * Dropout(Linear(Prompt))
        #    The dropout prevents noisy prompts in early epochs from destabilizing features.
        prompt_projected = self.prompt_dropout(self.prompt_proj(prompt))
        adapted_features = adapted_features + torch.tanh(self.gate) * prompt_projected

        return adapted_features, lid_logits, hx_new
